blank_issues_enabled: false
contact_links:
  - name: Project Milk Carton
    url: https://projectmilkcarton.org
    about: Visit our website for more information
  - name: Telegram Community
    url: https://t.me/ProjectMilkCarton
    about: Join our Telegram for questions and discussion
